spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
#  jackson:
#    default-property-inclusion: non_null
server:
  context-path: /sell

wechat:
  mpAppId: wxd889b96d5e406376
  mpAppSecret: 605f8813fb7c8216be096bf344c42959